/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class Interfaz extends javax.swing.JFrame {

    private final ArrayList<Forma> formas = new ArrayList<>();
    private ProxyCrearForma proxy = new ProxyCrearForma();

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Forma = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        x = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnClonar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        optRectangulo = new javax.swing.JRadioButton();
        optCirculo = new javax.swing.JRadioButton();
        optTriangulo = new javax.swing.JRadioButton();
        selectColor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PATRON PROTOTIPO, BRIDGE Y PROXY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 10, 520, 29);

        x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(x);
        x.setBounds(490, 170, 150, 50);

        y.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });
        jPanel1.add(y);
        y.setBounds(490, 260, 150, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("x");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 190, 30, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("y");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 270, 30, 30);

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear);
        btnCrear.setBounds(790, 200, 160, 50);

        btnClonar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClonar.setText("Clonar");
        btnClonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClonarActionPerformed(evt);
            }
        });
        jPanel1.add(btnClonar);
        btnClonar.setBounds(790, 280, 160, 50);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Forma", "X", "Y", "Color"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 470, 1060, 250);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(200, 80, 130, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rectangulo.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 230, 130, 90);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trinagulo.png"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(200, 340, 130, 110);

        Forma.add(optRectangulo);
        optRectangulo.setText("Rectangulo");
        jPanel1.add(optRectangulo);
        optRectangulo.setBounds(90, 260, 91, 25);

        Forma.add(optCirculo);
        optCirculo.setText("Circulo");
        jPanel1.add(optCirculo);
        optCirculo.setBounds(90, 130, 67, 25);

        Forma.add(optTriangulo);
        optTriangulo.setText("Triangulo");
        jPanel1.add(optTriangulo);
        optTriangulo.setBounds(100, 390, 83, 25);

        selectColor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Amarillo" }));
        jPanel1.add(selectColor);
        selectColor.setBounds(460, 360, 180, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (!x.getText().equals("") && !y.getText().equals("")) {
            String forma = formaSeleccionada();
            System.out.println("forma:" + forma);
            String color = selectColor.getSelectedItem().toString();
            System.out.println("color:" + color);
            Forma f = proxy.crear(forma, color, Integer.parseInt(x.getText()), Integer.parseInt(y.getText()));
            if (f != null) {
                model.addRow(new Object[]{forma, Integer.parseInt(x.getText()), Integer.parseInt(y.getText()), f.color()});
                formas.add(f);
                model.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(null, "No se pueden crear mas formas");
            }
            //model.addRow(new Object[]{"Circulo", Integer.parseInt(x.getText()), Integer.parseInt(y.getText()), null});
            //Circulo circulo = new Circulo(Integer.parseInt(x.getText()), Integer.parseInt(y.getText()));
            //formas.add(circulo);
            //model.fireTableDataChanged();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yActionPerformed

    private void btnClonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClonarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            Forma formaSeleccionada = formas.get(filaSeleccionada);
            Forma f = proxy.clonar(formaSeleccionada);
            if (f != null) {
                System.out.println("clonado");
                //Forma nuevaCopia = formaSeleccionada.clonar();
                formas.add(f);
                addShapeToTable(f);
            } else {
                JOptionPane.showMessageDialog(null, "No se pueden crear mas formas");
            }
        }
    }//GEN-LAST:event_btnClonarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    private void addShapeToTable(Forma shape) {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        if (shape instanceof Circulo) {
            Circulo circle = (Circulo) shape;
            tableModel.addRow(new Object[]{"Circulo", circle.x, circle.y, circle.color()});
        } else if (shape instanceof Rectangulo) {
            Rectangulo rectangle = (Rectangulo) shape;
            tableModel.addRow(new Object[]{"Rectangulo", rectangle.x, rectangle.y, rectangle.color()});
        } else if (shape instanceof Triangulo) {
            Triangulo triangle = (Triangulo) shape;
            tableModel.addRow(new Object[]{"Triangulo", triangle.x, triangle.y, triangle.color()});
        }
        tableModel.fireTableDataChanged();
    }

    private void limpiar() {
        x.setText("");
        y.setText("");
    }

    private String formaSeleccionada() {
        if (optCirculo.isSelected()) {
            return "Circulo";
        } else if (optRectangulo.isSelected()) {
            return "Rectangulo";
        } else if (optTriangulo.isSelected()) {
            return "Triangulo";
        }
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Forma;
    private javax.swing.JButton btnClonar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton optCirculo;
    private javax.swing.JRadioButton optRectangulo;
    private javax.swing.JRadioButton optTriangulo;
    private javax.swing.JComboBox<String> selectColor;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
